'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/app/component/Header";
import NextTopLoader from "nextjs-toploader";
import {Suspense} from "react";
import {Providers} from "@/app/GlobalRedux/provider";
import {NavigationEvents} from "@/app/utils/NavigationEvents";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Antonin Koreta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



    return (
    <html lang="fr">
      <body className={inter.className}>
      <Providers>
    <Header/>
          {children}
          <Suspense fallback={null}>
              <NavigationEvents/>
          </Suspense>
          <NextTopLoader color={'#5d5da8'} showSpinner={false}/>
      </Providers>
   </body>
    </html>
  )
}
